# Generated by Django 4.1.7 on 2023-03-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(choices=[('Community Center', 'Community Center'), ('Picnic Spot', 'Picnic Spot'), ('Swimming Pool', 'Swimming Pool'), ('Transport Service', 'Transport Service')], max_length=25)),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
