# Generated by Django 4.1.7 on 2023-03-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
