# Generated by Django 4.1.7 on 2023-03-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_d',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
